plugin: aws_ec2
boto_profile: DevOpsUser
strict: False
# ansible_host: ip_address
# ansible_host: private_ip_address
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region