---
    - name: Provision Web Servers
      hosts: tag_Name_app_timeisweb
      tasks:
    
        - name: Install pip3
          apt:
            update_cache: yes
            name: python3-pip
          become: yes
    
        - name: Install python docker sdk
          shell: |
            pip3 install docker
          become: yes
    
        - name: Install docker
          apt:
            name: docker.io
          become: yes
    
        - name: Start Docker
          shell: |
            systemctl start docker
            systemctl enable docker
          become: yes

        - name: Run image
          shell: docker run --name time_is_web -dit -p 80:80 -p 443:443 mailtech/appwebtime:latest
          become: yes